CREATE TABLE [dbo].[Averages]
(
	[Id] BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DeviceId NVARCHAR(64) NOT NULL,
	[Timestamp] DATETIMEOFFSET(7) NOT NULL,
	Value DECIMAL(18,3) NOT NULL, 
	[Count] INT NULL
)
